apiVersion: v1
kind: Pod # This example uses static pods launched by the kublet on each node, you may prefer to use deamonsets
metadata:
  name: fluentd
  namespace: kube-system
spec:
  containers:
  - name: fluentd
    image: quay.io/assemblyline/fluentd:latest
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
    command: ["bin/fluentd"]
    volumeMounts:
    - name: confd
      mountPath: /etc/fluent/conf.d
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
  terminationGracePeriodSeconds: 30
  volumes:
  - name: confd
    hostPath:
      path: /etc/fluent/conf.d # put your config files here, take a look at example/fluent.conf for an example
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
