apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: fluentd
        version: 0.0.1
      name: fluentd
    spec:
      containers:
      - name: fluentd
        image: quay.io/assemblyline/fluentd:0.0.1
        resources:
          limits:
            cpu: 100m
            memory: 564Mi
        command: ["bin/fluentd"]
        volumeMounts:
        - name: confd
          mountPath: /etc/fluent/conf.d
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: confd
        secret:
          secretName: fluentd
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
