FROM quay.io/assemblyline/buildpack_deps:15.10
MAINTAINER Ed Robinson<ed@a10e.org>

RUN echo "deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu vivid main" | tee /etc/apt/sources.list.d/ruby-ng.list \
  && echo "deb-src http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu vivid main" | tee -a /etc/apt/sources.list.d/ruby-ng.list \
  && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C3173AA6 \
  && apt-get update -q && apt-get install -qy --no-install-recommends \
       ruby<%= data['ruby'] %> \
       ruby<%= data['ruby'] %>-dev \
       libjemalloc1 \
       libsystemd-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && truncate -s 0 /var/log/*log \
  && gem install bundler

WORKDIR /usr/local/fluent

COPY Gemfile ./
COPY Gemfile.lock ./

RUN bundle install -j4 -r3

COPY bin/fluentd ./bin/

COPY fluent.conf /etc/fluent/fluent.conf
