FROM ubuntu:16.04
MAINTAINER Ed Robinson<ed@a10e.org>

WORKDIR /usr/local/fluent
COPY Gemfile Gemfile.lock ./

RUN echo "deb http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu xenial main" | tee /etc/apt/sources.list.d/ruby-ng.list \
  && echo "deb-src http://ppa.launchpad.net/brightbox/ruby-ng/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/ruby-ng.list \
  && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C3173AA6 \
  && apt-get update -q && apt-get install -qy --no-install-recommends \
       build-essential \
       ruby<%= data['ruby'] %> \
       ruby<%= data['ruby'] %>-dev \
       libjemalloc1 \
       libsystemd-dev \
  && gem install bundler --no-rdoc --no-ri \
  && bundle install -j4 -r3 \
  && apt-get remove -qy \
    build-essential \
    ruby<%= data['ruby'] %>-dev \
  && apt-get autoremove -qy \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && truncate -s 0 /var/log/*log

COPY bin/fluentd ./bin/
COPY fluent.conf /etc/fluent/fluent.conf
